---
title: "Avance3"
format: html
editor: visual
---

### Librerías

```{r message=FALSE}
library(readr)
library(dplyr)
library(ggplot2)
```

### Carga de la base de datos

```{r, message=FALSE}
#Encuentas <- read_csv("CAUTECResBien_1.csv")
#Ambientales<- read_csv("CAUTECResBien1_1.csv")
Encuentas <- read_csv("EncuestasB.csv")
Ambientales <- read_csv("MedicionesB.csv")
```

#### Unión de bases de datos

```{r, message=FALSE}
resultado <- inner_join(Encuentas, Ambientales , by = "ID")
```

#### Resultados

```{r}
cat("Filas en Encuestas:", nrow(Encuentas), "\n")
cat("Filas en Ambientales:", nrow(Ambientales), "\n")
cat("Filas después del join:", nrow(resultado), "\n")
```

```{r}
#names(resultado)

resultado <- resultado %>% select(
  -`Marca temporal.x`,
  -`Marca temporal.y`,
  -`¿En qué horario está llenando el formulario?.x`,
  -`¿En qué horario está llenando el formulario?.y`,
  - Piso.x,
  - Ambiente.x,
  -`¿Qué grupo lo/la está encuestando?`,
  -`¿En qué torre se encuentra?.x`,
  -...22,
  -...21
)
```

### Renombramiento y Selección

```{r}
resultado <- resultado %>% rename(
    'Torre' = `¿En qué torre se encuentra?.y`,
    'Piso' = Piso.y,
    'Ambiente' = Ambiente.y ,
    'Distractores' =`Tipo de distractores no relacionados con su propósito`,
    'Cant de luminarias'= `Cantidad de luminarias (focos) funcionando`,
    'Facilidad para estudiar' = `Nivel de facilidad para estudiar en el ambiente`,
    'Propósito' = `Propósito en la comunidad`,
    'Fuente de ruido' = `Fuente principal de ruido`
)
```

```{r}
resultado <- resultado %>% select(
  ID, Grupo, Torre, Ambiente, `Nivel de presión sonora (dB)`, `Nivel de iluminancia`, `Temperatura ambiental`, `N° de personas presentes`, `N° de tomacorrientes disponibles`, `Cant de luminarias`, `Fuente de luz` , `Fuente de ruido`,Propósito, Distractores, `Frecuencia de uso del ambiente` , `Nivel de conservación`,`Nivel de comodidad`, `Facilidad para estudiar`, `Intensidad de la luz`
)
```

### Limpieza

```{r}
resultado <- resultado %>% mutate(`Cant de luminarias` = case_when(
  `Cant de luminarias` == 'Todos' ~ NA,
  TRUE ~ `Cant de luminarias`
)) %>% mutate(`Cant de luminarias` = strtoi(`Cant de luminarias`))
```

```{r}
sum(is.na(resultado))
nrow(resultado)
resultado <- na.omit(resultado)
nrow(resultado)
```

```{r message=FALSE }
### Cuantitativas Discretas
resultado<- resultado %>% mutate(
  `N° de tomacorrientes disponibles` = as.numeric(`N° de tomacorrientes disponibles`),
  `N° de personas presentes` = as.numeric(`N° de personas presentes`)
)
#### Cuantitativas Continuas
resultado<- resultado %>%
  mutate(
    `Nivel de presión sonora (dB)` =
      round(as.numeric(`Nivel de presión sonora (dB)`), 2),

    `Nivel de iluminancia` =
      round(as.numeric(`Nivel de iluminancia`), 2)
  )

#### Factores Ordinales
resultado <- resultado %>%
  mutate(
    # Variables con escala del 1 al 5
    `Nivel de conservación` = factor(`Nivel de conservación`, levels = c(1:5), ordered = TRUE),
    `Nivel de comodidad` = factor(`Nivel de comodidad`, levels = c(1:5), ordered = TRUE),
    `Facilidad para estudiar` = factor(`Facilidad para estudiar`, levels = c(1:5), ordered = TRUE),
    
    # Variables con escala del 1 al 3
    `Intensidad de la luz` = factor(`Intensidad de la luz`, levels = c(1:3), ordered = TRUE),
    `Frecuencia de uso del ambiente` = factor(`Frecuencia de uso del ambiente`, levels = c(1:3), ordered = TRUE)
  )
#### Factores Nominales
resultado <- resultado%>% mutate(
  Propósito = as.factor(Propósito),
  `Fuente de luz` = as.factor(`Fuente de luz`),
  `Fuente de ruido` = as.factor(`Fuente de ruido`),
  Distractores = as.factor(Distractores),
  Ambiente = as.factor(Ambiente)
)
```

```{r}
str(resultado)
```

## 1. Análisis Univariable

**Nivel de presión sonora (dB) :**

```{r echo=FALSE}
cat("Media : ", round(mean(resultado$`Nivel de presión sonora (dB)`, na.rm = TRUE),2), "db\n")

cat("Mediana : ", round(median(resultado$`Nivel de presión sonora (dB)`, na.rm = TRUE),2), "db\n")

cat("Mínimo : ", min(resultado$`Nivel de presión sonora (dB)`, na.rm = TRUE), "db\n")

cat("Máximo : ", max(resultado$`Nivel de presión sonora (dB)`, na.rm = TRUE), "db\n")

cat("\n")

cat("Desviación estándar : ",
    round(sd(resultado$`Nivel de presión sonora (dB)`, na.rm = TRUE),2),
    "db\n")

cat("Rango intercuartílico : ",
    round(IQR(resultado$`Nivel de presión sonora (dB)`, na.rm = TRUE),2),
    "db\n")

cv_ruido <- sd(resultado$`Nivel de presión sonora (dB)`, na.rm = TRUE) /
             mean(resultado$`Nivel de presión sonora (dB)`, na.rm = TRUE) * 100

cat("Coeficiente de variación : ",
    round(cv_ruido,2),
    "%\n")
boxplot(
  resultado$`Nivel de presión sonora (dB)`,
  main = "Nivel de presión sonora",
  ylab = "dB"
)
```


**Nivel de Iluminancia : **
```{r echo=FALSE}
cat("Media : ", round(mean(resultado$`Nivel de iluminancia`, na.rm = TRUE),2), "lux\n")

cat("Mediana : ", round(median(resultado$`Nivel de iluminancia`, na.rm = TRUE),2), "lux\n")

cat("Mínimo : ", min(resultado$`Nivel de iluminancia`, na.rm = TRUE), "lux\n")

cat("Máximo : ", max(resultado$`Nivel de iluminancia`, na.rm = TRUE), "lux\n")

cat("\n")

cat("Desviación estándar : ",
    round(sd(resultado$`Nivel de iluminancia`, na.rm = TRUE),2),
    "lux\n")

cat("Rango intercuartílico : ",
    round(IQR(resultado$`Nivel de iluminancia`, na.rm = TRUE),2),
    "lux\n")

cv_ilum <- sd(resultado$`Nivel de iluminancia`, na.rm = TRUE) /
             mean(resultado$`Nivel de iluminancia`, na.rm = TRUE) * 100

cat("Coeficiente de variación : ",
    round(cv_ilum,2),
    "%\n")

boxplot(
  resultado$`Nivel de iluminancia`,
  main = "Nivel de iluminancia",
  ylab = "Lux"
)
```
